##### Commnad Echoing/Silencing #####
# all: 
# 	@echo "This is a silent command"
# 	echo "This is a loud command"
# 	cd ..; echo `pwd`

	
##### Default Shell #####
# SHELL=/bin/bash

# cool:
# 	echo "Hello from bash"
# 	sh_var="Hello from sh"; echo $$sh_var


##### Error Handling with -k -i and - #####
one:
	- false
	echo "This is a command after false"